version: 2
workflows:
  version: 2
  test:
    jobs:
      - build-and-release:
          filters:
            tags:
              only: /.*/
            branches:
              only:
                - main
jobs:
  build-and-release:
    machine: true
    steps:
      - checkout
      - run:
          name: Docker login
          command: scripts/release.sh docker-login
      - run:
          name: Make Build
          command: scripts/release.sh build
      - run:
          name: Release
          command: scripts/release.sh release
