version: 2
workflows:
  version: 2
  test:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
      - checks:
          filters:
            tags:
              only: /.*/
      - build-and-release:
          requires: [test, checks]
          filters:
            tags:
              only: /.*/
            branches:
              only:
                - main
jobs:
  test:
    docker:
      - image: darthjee/circleci_ruby_270:1.1.0
    steps:
      - checkout
      - run:
          name: Set folder
          command: cp source/* source/.??* ./ -r; rm source -rf
      - run:
          name: Prepare Coverage Test Report
          command: cc-test-reporter before-build
      - run:
          name: Bundle Install
          command: bundle install
      - run:
          name: RSpec
          command: bundle exec rspec
      - run:
          name: Coverage Test Report
          command: cc-test-reporter after-build --exit-code $?

  checks:
    docker:
      - image: darthjee/circleci_ruby_270:1.1.0
    steps:
      - checkout
      - run:
          name: Set folder
          command: cp source/* source/.??* ./ -r; rm source -rf
      - run:
          name: Bundle Install
          command: bundle install
      - run:
          name: Rubocop
          command: rubocop
  build-and-release:
    machine: true
    steps:
      - checkout
      - run:
          name: Check alreay built
          command: scripts/release.sh check-built
      - run:
          name: Docker login
          command: scripts/release.sh docker-login
      - run:
          name: Make Build
          command: scripts/release.sh build
      - run:
          name: Release
          command: scripts/release.sh release
