require: rubocop-rspec

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'

RSpec/DescribeClass:
  Exclude:
    - 'spec/integration/**/*_spec.rb'

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/Semicolon:
  Exclude:
    - spec/unit/route_spec.rb
    - spec/unit/application_spec.rb
    - spec/unit/endpoint_spec.rb
