# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.7.0'

gem 'arstotzka', '1.6.2'
gem 'sinatra',   '3.0.1'
gem 'sinclair',  '1.8.0'

group :development, :test do
  gem 'pry',        '0.14.1'
  gem 'pry-nav',    '1.0.0'
  gem 'simplecov',  '0.21.2'
end

group :development do
  gem 'rubocop',       '0.80.1'
  gem 'rubocop-rspec', '1.38.1'
end

group :test do
  gem 'rspec',                     '3.11.0'
  gem 'rspec-collection_matchers', '1.2.0'
  gem 'rspec-core',                '3.11.0'
  gem 'rspec-expectations',        '3.11.0'
  gem 'rspec-mocks',               '3.11.1'
  gem 'rspec-support',             '3.11.0'
  gem 'shoulda-matchers',          '4.3.0'
end
