# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.7.0'

gem 'arstotzka'
gem 'sinatra',   '3.0.1'
gem 'sinclair'

group :development, :test do
  gem 'pry'
  gem 'pry-nav'
  gem 'simplecov'
  gem 'reek'
  gem 'rubycritic'
end

group :development do
  gem 'rubocop'
  gem 'rubocop-rspec'
end

group :test do
  gem 'rack-test'
  gem 'rspec'
  gem 'rspec-collection_matchers'
  gem 'rspec-core'
  gem 'rspec-expectations'
  gem 'rspec-mocks'
  gem 'rspec-support'
  gem 'shoulda-matchers'
end
