# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.7.0'

gem 'sinatra', '3.0.1'
gem 'sinclair', '1.8.0'
gem 'arstotzka', '1.6.2'

group :development do
  gem 'rubocop',       '0.80.1'
end
